// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuiidqbgjywviwketsot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1aWlkcWJnanl3dml3a2V0c290Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTIxODIsImV4cCI6MjA3NDI4ODE4Mn0.jDiXRfcbEsD26X6gZTlROZuCOJf8ItHnuGFHvbYEoi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});