# Generated by Django 4.2.16 on 2025-10-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_otp_channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('voice', 'Voice Call'), ('sms', 'SMS')], default='whatsapp', help_text='Preferred method for receiving OTP codes', max_length=10),
        ),
    ]
