# Generated by Django 4.2.16 on 2025-10-26 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_payments', models.IntegerField(default=0)),
                ('total_payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_vendor_payouts', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('active_vendors', models.IntegerField(default=0)),
                ('vendors_with_payouts', models.IntegerField(default=0)),
                ('average_commission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('commission_to_revenue_ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Summary',
                'verbose_name_plural': 'Commission Summaries',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_type', models.CharField(choices=[('mpesa_stk_push', 'M-Pesa STK Push'), ('mpesa_c2b', 'M-Pesa C2B'), ('mpesa_b2c', 'M-Pesa B2C'), ('card_webhook', 'Card Payment Webhook')], max_length=20)),
                ('payload', models.JSONField(help_text='Raw webhook payload')),
                ('headers', models.JSONField(blank=True, help_text='Request headers', null=True)),
                ('processed_successfully', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Webhook Log',
                'verbose_name_plural': 'Payment Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payout_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer')], default='mpesa', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('recipient_number', models.CharField(help_text='M-Pesa number for payout', max_length=15)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for payout processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payout Request',
                'verbose_name_plural': 'Payout Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mpesaconfiguration',
            name='auto_process_payouts',
            field=models.BooleanField(default=True, help_text='Automatically process vendor payouts when payments complete'),
        ),
        migrations.AddField(
            model_name='mpesaconfiguration',
            name='default_commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Default commission rate for vendors (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='mpesaconfiguration',
            name='payout_processing_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed fee for processing payouts (KES)', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Zeno commission amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='payment',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Zeno commission rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='payment',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending Payout'), ('processed', 'Processed for Payout'), ('paid', 'Paid to Vendor')], default='pending', help_text='Status of vendor payout for this payment', max_length=20),
        ),
    ]
