# Generated by Django 4.2.16 on 2025-10-26 11:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0003_vendor_active_customers_count_and_more'),
        ('payments', '0002_commissionsummary_paymentwebhooklog_payoutrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vendor_earning',
            field=models.OneToOneField(blank=True, help_text='Linked vendor earning record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reference', to='vendors.vendorearning'),
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Vendor's share after commission", max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payout_status'], name='payments_pa_status_f92d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'vendor_earning'], name='payments_pa_order_i_4871a2_idx'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='paymentwebhooklog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentwebhooklog',
            name='payout_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='vendors.payouttransaction'),
        ),
        migrations.AlterUniqueTogether(
            name='commissionsummary',
            unique_together={('period_type', 'period_start', 'period_end')},
        ),
    ]
