# Generated by Django 4.2.16 on 2025-10-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_delivery_fee_vendor_delivery_radius_km_and_more'),
        ('services', '0001_initial'),
        ('orders', '0002_alter_order_options_cartitem_gas_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'service', 'gas_product')},
        ),
    ]
